ALTER TABLE public.pedidos
  ADD COLUMN IF NOT EXISTS programado_para TIMESTAMPTZ DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS metodo_pago TEXT NOT NULL DEFAULT 'mercadopago',
  ADD COLUMN IF NOT EXISTS espera_desde TIMESTAMPTZ DEFAULT NULL;